package NG.Living;

/**
 * A base set of stimuli
 * @author Geert van Ieperen created on 23-2-2019.
 */
public enum BaseStimulus implements StimulusType {
    /** negative status stimuli */
    DAMAGE, DEATH,

    /** positive status stimuli */
    REWARD, AFFECTION, RESPECT,

    /** neutral stimuli generated by an entity */
    ANNOYANCE,

    /** environmental auditory stimuli */
    FOOTSTEP, EXPLOSION, RUMBLE, SHOUT,

    /** environmental visual stimuli */
    FLASH,

    UNKNOWN;
}
